steps:
  # Build base image once
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        ".",
      ]

  # Tag for different services
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-fastapi:latest",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_worker:latest",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_beat:latest",
      ]

images:
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest"
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-fastapi:latest"
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_worker:latest"
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_beat:latest"
 
 gcloud artifacts repositories add-iam-policy-binding defi-backend --location=us-east1 --member=serviceAccount:489944993179-compute@developer.gserviceaccount.com --role="roles/artifactregistry.writer"

 gcloud projects add-iam-policy-binding delta-prop-shop --member="user:hatim@deltapropshop.io" --role="roles/artifactregistry.admin"
 gcloud artifacts repositories add-iam-policy-binding defi-backend --location=us-east1 --member="serviceAccount:489944993179-compute@developer.gserviceaccount.com" --role="roles/artifactregistry.writer"