steps:
  # Build base image once
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        ".",
      ]

  # Tag for different services
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-fastapi:latest",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_worker:latest",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_beat:latest",
      ]

images:
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base:latest"
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-fastapi:latest"
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_worker:latest"
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-celery_beat:latest"
