steps:
  # Build base image once
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "CACHEBUST=${BUILD_ID}",
        "-t",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base/api:latest",
        ".",
      ]

  # Tag for different services
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base/api:latest",
        "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-fastapi/api:latest",
      ]

images:
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-base/api:latest"
  - "us-east1-docker.pkg.dev/delta-prop-shop/defi-backend-fastapi/api:latest"
