# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY . /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run celery workers directly using shell form of CMD
CMD bash -c "\
    celery -A src.core.celery_app worker -n position_worker --loglevel=info -Q position_monitoring & \
    celery -A src.core.celery_app worker -n redis_worker --loglevel=info -Q event_listener & \
    celery -A src.core.celery_app worker -n notification_worker --loglevel=info -Q send_notifications & \
    celery -A src.core.celery_app worker -n mainnet_challenges --loglevel=info -Q monitor_mainnet_challenges & \
    celery -A src.core.celery_app worker -n monitor_miner --loglevel=info -Q monitor_miner & \
    celery -A src.core.celery_app worker -n monitor_testnet --loglevel=info -Q testnet_validator & \
    celery -A src.core.celery_app worker -n tournament_notifications_worker --loglevel=info -Q tournament_notifications & \
    wait -n"