name: Run Actions

on:
  push:
    branches:
      - api-v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build fastapi image
        run: docker build . -t fastapi

      - name: Login ECR Repository
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 288792505174.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag and push defi-fastapi-container
        run: |
          docker tag sn8_trading_app-fastapi:latest 288792505174.dkr.ecr.us-east-1.amazonaws.com/defi-backend-fastapi:latest    
          docker push 288792505174.dkr.ecr.us-east-1.amazonaws.com/defi-backend-fastapi:latest

      - name: Deploy ECS task
        run: |
          aws ecs update-service \
            --cluster arn:aws:ecs:us-east-1:288792505174:cluster/DefiTradingCluster \
            --service Defi-Backend \
            --force-new-deployment
